"""Add ItemRecebido model for user received items

Revision ID: 64cbe2628aa6
Revises: 67c3b5cf3152
Create Date: 2026-05-08 16:18:12.319981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64cbe2628aa6'
down_revision = '67c3b5cf3152'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
