"""Add employee information fields to User model

Revision ID: 68a9d7f2e5c3
Revises: 67c3b5cf3152
Create Date: 2026-05-13 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '68a9d7f2e5c3'
down_revision = '67c3b5cf3152'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Add new employee information columns to users table"""
    # ### commands auto generated by Alembic - please adjust! ###

    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = {col['name'] for col in inspector.get_columns('users')}

    columns_to_add = [
        ('empresa', sa.Column('empresa', sa.String(255), nullable=False, server_default='')),
        ('cnpj', sa.Column('cnpj', sa.String(18), nullable=False, server_default='')),
        ('endereco', sa.Column('endereco', sa.String(500), nullable=False, server_default='')),
        ('cargo', sa.Column('cargo', sa.String(255), nullable=False, server_default='')),
        ('cpf', sa.Column('cpf', sa.String(14), nullable=False, server_default='')),
        ('data_admissao', sa.Column('data_admissao', sa.Date(), nullable=True)),
        ('departamento', sa.Column('departamento', sa.String(255), nullable=False, server_default='')),
        ('local_trabalho', sa.Column('local_trabalho', sa.String(255), nullable=False, server_default='')),
    ]

    for column_name, column_def in columns_to_add:
        if column_name not in existing_columns:
            op.add_column('users', column_def)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove employee information columns from users table"""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop columns from users table
    op.drop_column('users', 'local_trabalho')
    op.drop_column('users', 'departamento')
    op.drop_column('users', 'data_admissao')
    op.drop_column('users', 'cpf')
    op.drop_column('users', 'cargo')
    op.drop_column('users', 'endereco')
    op.drop_column('users', 'cnpj')
    op.drop_column('users', 'empresa')
    
    # ### end Alembic commands ###
