"""Add TermoEntrega model for equipment delivery and responsibility

Revision ID: 69d8e3f9c4d7
Revises: 68a9d7f2e5c3
Create Date: 2026-05-13 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d8e3f9c4d7'
down_revision = '68a9d7f2e5c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create termos_entrega table"""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table(
        'termos_entrega',
        sa.Column('id_termo', sa.Integer(), nullable=False),
        sa.Column('id_usuario', sa.Integer(), nullable=False),
        sa.Column('empresa', sa.String(255), nullable=False, server_default=''),
        sa.Column('cnpj', sa.String(18), nullable=False, server_default=''),
        sa.Column('endereco', sa.String(500), nullable=False, server_default=''),
        sa.Column('nome_colaborador', sa.String(255), nullable=False, server_default=''),
        sa.Column('cargo_funcao', sa.String(255), nullable=False, server_default=''),
        sa.Column('cpf_cnpj', sa.String(18), nullable=False, server_default=''),
        sa.Column('departamento', sa.String(255), nullable=False, server_default=''),
        sa.Column('local_trabalho', sa.String(255), nullable=False, server_default=''),
        sa.Column('data_admissao', sa.Date(), nullable=True),
        sa.Column('equipamentos', sa.Text(), nullable=True, server_default='[]'),
        sa.Column('data_criacao', sa.DateTime(), nullable=False),
        sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
        sa.Column('assinado', sa.Boolean(), nullable=False, server_default='0'),
        sa.Column('data_assinatura', sa.DateTime(), nullable=True),
        sa.Column('observacoes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['id_usuario'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id_termo')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop termos_entrega table"""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('termos_entrega')
    
    # ### end Alembic commands ###
